### ISSUE TITLE
boost noncopyable for scoped goodness

### ISSUE THREAD

**Issue by hluisi** [simongeilfus/Cinder-ImGui#20]
Cinder is moving away from boost, so you may want update using #include "cinder/Noncopyable.h" instead.  :)

**Comment by WhileRomeBurns** [comment]
That's the only way it compiles without error for me (Cinder 0.9.0 / vcpp 2015). Include **"cinder/Noncopyable.h"** and replace all instances of ** boost::noncopyable** with** ci::Noncopyable**.

**Comment by simongeilfus** [comment]
Thanks guys and sorry for the slow update!
