### ISSUE TITLE
Clipboard functions on linux

### ISSUE THREAD

**Issue by naychrist** [simongeilfus/Cinder-ImGui#22]
Not sure if this error is better addresses on Cinder repo Linux branch as don't understand what is going on but despite Clipboard.h being present and functions existing I get:

`CMakeFiles/Cicada.dir/home/renechristen/Applications/_cinder/Cinder.git/blocks/Cinder-ImGui/src/CinderImGui.cpp.o: In function `operator()':
/home/renechristen/Applications/_cinder/Cinder.git/blocks/Cinder-ImGui/src/CinderImGui.cpp:932: undefined reference to `cinder::Clipboard::getString()'
/home/renechristen/Applications/_cinder/Cinder.git/blocks/Cinder-ImGui/src/CinderImGui.cpp:928: undefined reference to `cinder::Clipboard::setString(std::string const&)'
`

**Comment by simongeilfus** [comment]
Hey,
Yes I guess it's more related to Cinder's Android; You're apparently missing some symbols. Easy way to make sure would be to create an empty linux app and call ```ci::Clipboard::getString()``` to see if you have the same symbols missing. 

You should probably ask Hai, Clipboard support is maybe still a wip on linux, I have no idea!

**Comment by PetrosKataras** [comment]
Hi from me also,

currently there is no Clipboard support on Linux. I m not sure how important is Clipboard support for the GUI to work but from a quick look its seems its just used in a couple of callbacks so maybe you can try to comment out [these](https://github.com/simongeilfus/Cinder-ImGui/blob/5a89fe6dcfc89b99bede6926125502db5c2a7b81/src/CinderImGui.cpp#L923-L937) lines and see how this works for you ?

**Comment by simongeilfus** [comment]
I'm going to close this as it's more a Cinder Linux issue...

**Comment by naychrist** [comment]
Just a note that wapping those lines @PetrosKataras highlighted in an `#ifndef CINDER_LINUX` gets it working fine on Ubuntu.
