### ISSUE TITLE
git in cinderblock.xml

### ISSUE THREAD

**Issue by naychrist** [simongeilfus/Cinder-ImGui#24]
Hey, any chance you could add the following attribute to your cinderblock.xml file so that Tinderbox can add it to projects as a submodule?

`git="git@github.com:simongeilfus/Cinder-ImGui.git"`

**Comment by simongeilfus** [comment]
Of course. Here you go:
https://github.com/simongeilfus/Cinder-ImGui/commit/a45062f916e7e1a90b2ec647c17bc7f85075555a
