### ISSUE TITLE
imgui folder empty

### ISSUE THREAD

**Issue by Dazzid** [simongeilfus/Cinder-ImGui#26]
Hi,
I think there is a mistake on the project. It doesn't include any file inside lib/imgui folder; then Xcode doesn't find "imgui.h" and the rest.

How can I try this block?
Thanks

David

**Comment by gaborpapp** [comment]
Hi David,

It's a git submodule, which should be inited. You can do it with these commands in the repo root folder:

```
git submodule init
git submodule update
```

More info:
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by Dazzid** [comment]
Ah cool! 
Thanks for the info. The GUI is great!
