### ISSUE TITLE
Could not build

### ISSUE THREAD

**Issue by 0x0c** [simongeilfus/Cinder-ImGui#27]
Hello

I cannot build this block the following errors.
![screen shot 2016-04-17 at 8 48 31 am](https://cloud.githubusercontent.com/assets/154327/14584277/414430c6-0479-11e6-9ada-829aa9502c1f.png)

When I comment out these code, it works fine.
How to fix this errors?

I'm using
- Cinder 0.9.0
- OSX 10.11.4
- ImGUI https://github.com/ocornut/imgui/commit/af46ca2b4c0e9039ef5e96753fd49ae979ceaf75

**Comment by simongeilfus** [comment]
Hi,
You have a too recent version of imgui, which means you probably haven't setup the submodule properly.

Use the following to clone this block properly and it should work :
```
git clone https://github.com/simongeilfus/Cinder-ImGui.git
git submodule init
git submodule update
```
If you didn't init the submodule yet, you can probably delete the content of the lib folder and run the two last commands above.

**Comment by simongeilfus** [comment]
I'll push an update with the latest imgui soon.

**Comment by 0x0c** [comment]
Thank you for your reply.
I'm waiting for the update!
