### ISSUE TITLE
signals::ConnectionList Error

### ISSUE THREAD

**Issue by xumo** [simongeilfus/Cinder-ImGui#36]
The line 925 
`static signals::ConnectionList sWindowConnections;`
throws a compiler error:
`/Users/rodrigo/Herramientas/cinder_0.9.0_mac/blocks/Cinder-ImGui/src/CinderImGui.cpp:925:17: No type named 'ConnectionList' in namespace 'cinder::signals'; did you mean 'Connection'?`

**Comment by gaborpapp** [comment]
Try updating cinder or roll back Cinder-ImGui before a57f4c9a0

**Comment by xumo** [comment]
That worked. Thanks.
