### ISSUE TITLE
Update Imgui to fix failing assertion

### ISSUE THREAD

**Issue by naychrist** [simongeilfus/Cinder-ImGui#37]
Hi, I occasionally get this crash:

`Assertion failed: (g.IO.DeltaTime >= 0.0f), function NewFrame, file /Applications/_cinder/CinderApps/ross_smith/ornicube/Ornicube/blocks/ImGui/lib/imgui/imgui.cpp, line 2089.`

Which was reported to Imgui [here](https://github.com/pioneerspacesim/pioneer/pull/3854) and resolved [here](https://github.com/pioneerspacesim/pioneer/pull/3854)

any chance of updating the Imgui submodule to include this fix?

**Comment by pholz** [comment]
came across the same issue, found it hard to reproduce so far, but #38 should fix it analogous to the fix you referenced

**Comment by drewish** [comment]
@naychrist Based on the links you provided I'm not sure what you mean by reported to Imgui. That looks like a different project.

**Comment by naychrist** [comment]
@drewish - yes sorry it is indeed another project that uses Imgui, seems the check needs to happen outside Imgui as in the fix from @pholz above. I have not had a chance to test this fix properly yet - the error is very sporadic but can appear when imgui is left drawing to screen in cinder for a long time (sometimes hours).
