### ISSUE TITLE
Projects reference missing include/imgui_user.* files

### ISSUE THREAD

**Issue by drewish** [simongeilfus/Cinder-ImGui#41]
It looks like they were removed in https://github.com/simongeilfus/Cinder-ImGui/commit/02a331d10c1079c274bbe335b73bb01fac3e4583 but not removed from `cinderblock.xml`.

**Comment by simongeilfus** [comment]
Thanks! This should be fixed in https://github.com/simongeilfus/Cinder-ImGui/commit/eaa9eb51f3ead211a98e46a87d56342e3152180a
