### ISSUE TITLE
ImFontAtlas::Build() crash on windows

### ISSUE THREAD

**Issue by q-depot** [simongeilfus/Cinder-ImGui#46]
Hi,

loading a custom font crash on windows, I tried both Roboto and FontAwesome, so I assume the fonts are fine, the same code works just fine on mac.

```
std::vector<ImWchar>                    iconsRange  = { ICON_MIN_FA, ICON_MAX_FA, 0 };
std::vector<ImWchar>                    textRange   = { 0x0001, 0x00BF, 0 };
std::vector<std::pair<fs::path,float>>  fontPaths;
   
fontPaths.push_back( make_pair<fs::path,float>( getAssetPath("fonts/Roboto/Roboto-Regular.ttf"), 13.0f ) );
fontPaths.push_back( make_pair<fs::path,float>( getAssetPath("fonts/fontawesome-webfont.ttf"), 12.0f ) );
    
ui::initialize( ui::Options().fonts( fontPaths, true )
                    .fontGlyphRanges( "fontawesome-webfont", iconsRange )
                    .fontGlyphRanges( "Roboto-Regular", textRange ) );
```
The code breaks in ImFontAtlas::Build()

any idea?

**Comment by q-depot** [comment]
I'm debugging the build function and I believe this is something to do with the glyphs range that somehow goes bananas and the glyps count returns a negative number

imggui_draw.cpp #1291
`
            cfg.GlyphRanges = GetGlyphRangesDefault();
        for (const ImWchar* in_range = cfg.GlyphRanges; in_range[0] && in_range[1]; in_range += 2)
        {
			ci::app::console() << "add range " << in_range[1] << " " << in_range[0] << " " << (in_range[1] - in_range[0] + 1 ) << std::endl;
            total_glyph_count += (in_range[1] - in_range[0]) + 1;
            total_glyph_range_count++;
        }
    }

	ci::app::console() << "total_glyph_count " << total_glyph_count << std::endl;
`

**Comment by q-depot** [comment]
I think I found the problem, I'm not sure why this was working on osx, but not on windows.
The problem was the glyps range in addFont() which should be null terminated in order for imgui to exit the loop mentioned above.

I can send you a pull request if you want:
https://github.com/q-depot/Cinder-ImGui/commit/56d50c92870af1a57efa3f8307c2f70d3c21f19d

**Comment by simongeilfus** [comment]
Thanks for this and sorry for the usual slow process reviewing PRs!.
