### ISSUE TITLE
CinderImGui.cpp window->DC.ButtonRepeat

### ISSUE THREAD

**Issue by Nesetalis** [simongeilfus/Cinder-ImGui#52]
There is a recent change that moves ButtonRepeat to a new location. The Cinder-ImGui code will need to be modified to reflect this change.

**Comment by simongeilfus** [comment]
Should be fixed in https://github.com/simongeilfus/Cinder-ImGui/commit/83a80eb68a7427e8de4d693c01baa741267997ce 
Let me know if that works for you
