### ISSUE TITLE
library submodule commit id still in folder name

### ISSUE THREAD

**Issue by interwebjill** [simongeilfus/Cinder-ImGui#58]
...so it doesn't work with Tinderbox:

https://github.com/simongeilfus/Cinder-ImGui/tree/master/lib

**Comment by simongeilfus** [comment]
No sure why this would happen. Is that folder empty? Have you `git submodule init` ?

**Comment by interwebjill** [comment]
I should have clarified, sorry. In the github repo, the title of the folder
reads imgui @ 398a4e1. The effect was that when I download the zip file,
the Cinder-ImGui-master/lib/imgui directory is empty.

I didn't clone the repo.

**Comment by simongeilfus** [comment]
That's how github and submodule work. You will only see the commit id in the folder name in github, and if you download the zip instead of doing `git clone https://github.com/simongeilfus/Cinder-ImGui --recursive` you won't get ImGui submodule.
