### ISSUE TITLE
xcode samples dont work

### ISSUE THREAD

**Issue by Ahbee** [simongeilfus/Cinder-ImGui#60]
i ran into these problems when trying to run with xcode

1. ui::ShowDemoWindow() does not exist should be ui::ShowTestWindow();
2. path to cinder libs is wrong should be "$(CINDER_PATH)/lib/macosx/Debug/libcinder.a" and
"$(CINDER_PATH)/lib/macosx/Release/libcinder.a"
3. crashes as soon as you start the example in `ImGuiWindow*  GetCurrentWindow()`

**Comment by simongeilfus** [comment]
You probably need to update imgui submodule. `Imgui::ShowTestWindow()` has been deprecated longtime ago. Try `git submodule update` at the root of the repo.

**Comment by Ahbee** [comment]
Hi so sorry about that, i ran the update but I am still getting the crash as soon I start the example
<img width="1327" alt="crash" src="https://user-images.githubusercontent.com/6386895/37009540-620e3090-20b5-11e8-8f3d-4fc8e9551387.png">

**Comment by Ahbee** [comment]
I have mac osx 10.13.3

**Comment by simongeilfus** [comment]
I'll try to find a mac to test this tomorrow.

**Comment by Ahbee** [comment]
ok thanks so much, yeah it crashes every time i try to resize the window

**Comment by simongeilfus** [comment]
In the meantime, I think a workaround could be to set [`ui::Options().autoRender`](https://github.com/simongeilfus/Cinder-ImGui/blob/master/include/CinderImGui.h#L82) to `false` when initializing ImGui and take care of calling `ui::NewFrame` / `ui::Render` yourself.
My guess is that when resizing the window you end up having two `ui::Render` for one `ui::NewFrame`, which ImGui doesn't like.

**Comment by chewie54** [comment]
I'm also having the same issue.   Could you provide a code snippet with the fix you suggested in the last message.   I'm new to imgui and cinder and glw3.  I was able to create a Imgui project with Tinder created and added ImGui::initialize to the cinder_imguiApp::setup() and the following to cinder_imguiApp::draw()

    bool show_demo_window = true;
	gl::clear( Color( 0, 0, 0 ) );
    if (show_demo_window)
    {
        ImGui::SetNextWindowPos(ImVec2(650, 20), ImGuiCond_FirstUseEver); // Normally user code doesn't need/want to call this because positions are saved in .ini file anyway. Here we just want to make the demo initial state a bit more friendly!
        ImGui::ShowDemoWindow(&show_demo_window);
    }}  

Thanks

**Comment by simongeilfus** [comment]
Initialize ImGui like this in your setup or App constructor:
```c++
void MyApp::setup()
{
     ui::initialize( ui::Options().autoRender( false ) );
}
```

Then manually call `ui::NewFrame` and `ui::Render` like this:
```c++
void MyApp::update()
{
      ui::NewFrame();
      // keep all your imgui code between those two calls 
      ui::Render();
}
```

**Comment by chewie54** [comment]
It fails now at line 3274 of imgui.cpp:
    
IM_ASSERT((g.FrameCount == 0 || g.FrameCountEnded == g.FrameCount)  && "Forgot to call 
Render() or EndFrame() at the end of the previous frame?");

Thanks for helping.

**Comment by bdon** [comment]
revisions before a777589e30160b2a528495da5d58421e9eea7712 work fine on macOS
