### ISSUE TITLE
Multi ImGUI Windows on Multi Cinder Windows

### ISSUE THREAD

**Issue by VincentPT** [simongeilfus/Cinder-ImGui#62]
Hi, this is not actually an issue.
I am new to Cinder and OpenGL.
I'm getting stuck on creating ImGUI Windows on Multi Cinder's Window.

Everything is fine if application have some ImGUI windows on  single Cinder's window.
But when it open the second Cinder's window, it crashes and generates bellow errors:

|warning| cinder::gl::VaoImplCore::bindImpl[77] VAO bound against different context from allocation. Reassigning context.
Assertion failed!

Program: ...or\jellyfish\build\GoCrypto\Debug\cinder_imgui.dll
File: e:\projects\externals\cinder\blocks\cinder-...\imgui.cpp
Line: 4432

Expression: g.FrameCountEnded != g.FrameCount'

Does sound like ImGUI does not support dispplay multi windows on Multi Cinder's windows?

**Comment by brucelane** [comment]
I doing like this 
```
void VDUI::resize() {
	mIsResizing = true;
	// disconnect ui window and io events callbacks
	ui::disconnectWindow(getWindow());
}
void VDUI::draw() {
	ImGuiStyle& style = ui::GetStyle();

	if (mIsResizing) {
		mIsResizing = false;

		// set ui window and io events callbacks 
		ui::connectWindow(getWindow());
		ui::initialize();
...
```

**Comment by simongeilfus** [comment]
This is currently not supported in this wrapper but will be soon. You can have a look at [this branch](https://github.com/ocornut/imgui/tree/viewport) in the meantime. I'll work on integrating this as soon as it is merged into master.

**Comment by VincentPT** [comment]
@simongeilfus , thank you. Are you ocornut?

**Comment by brucelane** [comment]
He is not Omar Cornut.
Yes, my hack isn't very stable...
